FROM public.ecr.aws/lambda/python:3.9
WORKDIR ${LAMBDA_TASK_ROOT}
COPY ./BaseRecognitionModule.py ${LAMBDA_TASK_ROOT}
COPY ./cubicObj_utils.py ${LAMBDA_TASK_ROOT}
COPY ./sceneUnderstandingModule ${LAMBDA_TASK_ROOT}/sceneUnderstandingModule/
RUN pip install -r ${LAMBDA_TASK_ROOT}/sceneUnderstandingModule/requirements.txt
CMD [ "sceneUnderstandingModule/lambda_function.handler" ]