FROM public.ecr.aws/lambda/python:3.9
WORKDIR ${LAMBDA_TASK_ROOT}
COPY ./BaseRecognitionModule.py ${LAMBDA_TASK_ROOT}
COPY ./cubicObj_utils.py ${LAMBDA_TASK_ROOT}
COPY ./awsLocalizationModule ${LAMBDA_TASK_ROOT}/awsLocalizationModule/
RUN pip install -r ${LAMBDA_TASK_ROOT}/awsLocalizationModule/requirements.txt
CMD [ "awsLocalizationModule/lambda_function.handler" ]